### ISSUE TITLE
Flag shortcuts

### ISSUE THREAD

**Issue by MedBooster** [Liresol/anki-custom-shortcuts#156]
I am actively using my keyboard shortcuts for flag 1-4.
Is there a way to link keyboard shortcuts to flag 5-7 yet? (pink, turquoise and purple)

**Comment by Liresol** [comment]
Hello,
I've just pushed out an update for this which adds support for the new flags.
If you have any issues with the new shortcuts, let me know and I will look into it further.

**Comment by ghost** [comment]
"window_browser flag_pink": "Ctrl+5",
    "window_browser flag_turquoise": "Ctrl+6",
    "window_browser flag_purple": "Ctrl+7",
    
These shortcuts are still not working, even when added manually. If indeed you did add support for them I also suggest putting these options in the default config.
